/* Generated By:JJTree: Do not edit this line. */

package com.krine.lang.ast;

public class KrineFormalComment extends SimpleNode {
    public String text;

    public KrineFormalComment(int id) {
        super(id);
    }

}
