/* Generated By:JJTree: Do not edit this line. BSHFormalComment.java */

package com.dragon.lang.ast;

public class DragonFormalComment extends SimpleNode {
    public String text;

    public DragonFormalComment(int id) {
        super(id);
    }

}
